/**
 * This will not scale well with localization and the size the term bank will grow.
 * This is a temporary solution until a better system can be thought out.
 *  */ 
export const termFilter = [
    "blockchain",
    "hodl",
    "fud",
    "fomo",
    "fiat",
    "whale",
    "ethereum",
    "arweave",
    "bitcoin",
    "web3",
    "fungible",
    "non-fungible",
    "gm",
    "nft",
    "wagmi",
    "ngmi",
    "igmi",
    "dao",
    "glosseta",
    "probably nothing",
    "gas",
    "irl",
    "gn",
    "ga",
    "minting",
    "lazy minting",
    "eip",
    "hash",
    "wallet",
    "cryptocurrency",
    "ygmi",
    "staking",
    "token",
    "developer dao",
    "open source",
    "dex",
    "altcoin",
    "dapp",
    "frens",
    "web2",
    "decentralized",
    "web1",
    "ens",
    "hot wallet",
    "cold wallet",
    "amm",
    "peer",
    "proof of work",
    "beacon chain",
    "proof of stake",
    "public key",
    "private key",
    "sidechain",
    "layer 1",
    "layer 2",
    "blockchain trilema",
    "block",
    "solana",
    "proof of history",
    "centralized",
    "sharding",
    "airdrops",
    "zero-knowledge proof",
    "digital identity"
];