// This will not scale well with localization and the size the term bank will grow
export const termFilter = [
    "blockchain",
    "hodl",
    "fud",
    "fomo",
    "fiat",
    "whale",
    "ethereum",
    "arweave",
    "bitcoin",
    "web3",
    "fungible",
    "non-fungible",
    "gm",
    "nft",
    "wagmi",
    "ngmi",
    "igmi",
    "dao",
    "glosseta",
    "probably nothing",
    "gas",
    "irl",
    "gn",
    "ga",
    "minting",
    "lazy minting",
    "eip",
    "hash",
    "wallet",
    "cryptocurrency",
    "ygmi",
    "staking",
    "token",
    "developer dao",
    "open source",
    "dex",
    "altcoin",
    "dapp",
    "frens",
    "web2",
    "decentralized",
    "web1",
    "ens",
    "hot wallet",
    "cold wallet"
];