import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { getWalletBalance } from "./api/arweave/arweave-client";
import { Button, ButtonGroup } from "@chakra-ui/button";
import { SearchIcon } from "@chakra-ui/icons";
import {
  HStack,
  VStack,
  Input,
  Heading,
  InputGroup,
  InputLeftElement,
  Skeleton,
  SkeletonCircle,
  SkeletonText,
  Box,
} from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { fetchTransactionsForWallet } from "./api/arweave/arweave-client";

const Home: NextPage = () => {
  const [balance, setBalance] = useState(0 as number);
  const [showBalance, setShowSetBalance] = useState(false);

  useEffect(() => {
    if (balance > 0) {
      setShowSetBalance(true);
    }
  }, [balance]);

  const fetchArBalance = async () => {
    let res = await fetchTransactionsForWallet(
      "FWh7-V_t6BHFNwoTLpQOj3w62TxXE7teHW9opgrCMqE"
    );
    console.log(res);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Glosseta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading className={styles.title}>Glosseta</Heading>
      <main className={styles.main}>
        <VStack>
          <HStack spacing={3}>
            <InputGroup>
              <InputLeftElement
                className="InputLeft"
                pointerEvents="none"
                children={
                  <SearchIcon className="SearchIcon" color="gray.300" />
                }
                size="xs"
              />
              <Input
                size="md"
                variant="outline"
                placeholder="Search the metaverse"
                backgroundColor="white"
                rounded="lg"
              />
            </InputGroup>
            <Button onClick={fetchArBalance}>Search</Button>
          </HStack>
        </VStack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
