import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { Button, ButtonGroup } from "@chakra-ui/button";
import { SearchIcon } from "@chakra-ui/icons";
import {
  HStack,
  VStack,
  Input,
  Heading,
  InputGroup,
  InputLeftElement,
  Text,
  Skeleton,
  SkeletonCircle,
  SkeletonText,
  Box,
} from "@chakra-ui/react";
import { useState, useEffect, SetStateAction } from "react";

const Home: NextPage = () => {
  const [searchTerm, setSearchTerm] = useState("");

  const handleSearchTermChange = (event: {
    target: { value: SetStateAction<string> };
  }) => setSearchTerm(event.target.value);

  return (
    <div className={styles.container}>
      <Head>
        <title>Glosseta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading className={styles.title}>Glosseta</Heading>
      <main className={styles.main}>
        <VStack>
          <HStack spacing={3}>
            <InputGroup>
              <InputLeftElement
                className="InputLeft"
                pointerEvents="none"
                children={
                  <SearchIcon className="SearchIcon" color="gray.300" />
                }
                size="xs"
              />
              <Input
                size="md"
                variant="outline"
                placeholder="Search the metaverse"
                backgroundColor="white"
                rounded="lg"
                onChange={handleSearchTermChange}
              />
            </InputGroup>
            <Link
              href={{
                pathname: "/search",
                query: { term: searchTerm.toLowerCase() },
              }}
            >
              <Button>Search</Button>
            </Link>
          </HStack>
        </VStack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
